name: Trigger auto deployment for container-app-7gf2jd6fks6qc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-7gf2jd6fks6qc-AutoDeployTrigger-cd48f17e-640f-4d57-844e-5bd1b4020606.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP7GF2JD6FKS6QC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP7GF2JD6FKS6QC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP7GF2JD6FKS6QC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP7GF2JD6FKS6QC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP7GF2JD6FKS6QC_REGISTRY_PASSWORD }}
          containerAppName: container-app-7gf2jd6fks6qc
          resourceGroup: appspacesragappb13d9f56
          imageToBuild: default/container-app-7gf2jd6fks6qc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


